server:
  port: 8009
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.108.128:3306/springbootdata?characterEncoding=utf-8
    username: root
    password: LiRuYi@666
mybatis:
  type-aliases-package: com.lagou.pojo
  configuration:
    map-underscore-to-camel-case: true
