server:
  port: 8002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.108.128:3306/springbootdata?characterEncoding=utf-8
    username: root
    password: LiRuYi@666
  redis:
    host: 192.168.108.128
    port: 6379
    jedis:
      pool:
        max-active: 18
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 3000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lagou.bootmybatis.pojo

